# roles/postgres/handlers/main.yml

---
- name: restart postgresql
  ansible.builtin.service:
    name: postgresql
    state: restarted

- name: restart patroni
  ansible.builtin.service:
    name: patroni
    state: restarted

- name: restart zabbix-server-pgsql
  ansible.builtin.service:
    name: zabbix-server-pgsql
    state: restarted

- name: restart zabbix-agent
  ansible.builtin.service:
    name: zabbix-agent
    state: restarted
