---
- name: Configurar Zabbix Server e Web
  hosts: zabbix_servers
  become: true

  tasks:
    - name: Instalar Zabbix Server e Web
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - zabbix-server-pgsql
        - zabbix-frontend-php
        - zabbix-frontend-apache

    - name: Copiar arquivos de configuração do Zabbix Server
      copy:
        src: files/zabbix_server.conf
        dest: /etc/zabbix/zabbix_server.conf

    - name: Copiar arquivos de configuração do Zabbix Web
      copy:
        src: files/zabbix.conf.php
        dest: /etc/zabbix/web/zabbix.conf.php
