---
- name: Configurar servidores PostgreSQL
  hosts: database_servers
  become: yes
  become_user: root
  vars_files:
    - vars.yml
    - vault.yml
  vars:
    #ansible_become_pass_file: vault.yml
    ansible_become_pass: 12345
  tasks:
    - name: Add PostgreSQL repository key
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present
        
    - name: Add PostgreSQL repository
      apt_repository:
        repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
        state: present  
        
    - name: Instalar PostgreSQL e TimescaleDB
      apt:
        name: ['postgresql', 'postgresql-contrib', 'timescaledb-postgresql']

    - name: Configurar PostgreSQL
      template:
        src: postgresql.conf.j2
        dest: /etc/postgresql/{{ postgres_version }}/main/postgresql.conf
      notify: Restart PostgreSQL

    - name: Configurar TimescaleDB
      command: sudo -u postgres psql -d {{ db_name }} -c "CREATE EXTENSION IF NOT EXISTS timescaledb;"
      notify: Restart PostgreSQL

    - name: Configurar replicação
      template:
        src: pg_hba.conf.j2
        dest: /etc/postgresql/{{ postgres_version }}/main/pg_hba.conf
      notify: Restart PostgreSQL

    - name: Criar diretório de dados
      file:
        path: /data
        state: directory
        owner: postgres
        group: postgres

  handlers:
    - name: Restart PostgreSQL
      service:
        name: postgresql
        state: restarted
