---
- name: Configurar servidores Zabbix
  hosts: zabbix_servers
  vars_files:
    - vars.yml 
  tasks:
    - name: Instalar Zabbix Server
      apt:
        name: ['zabbix-server-pgsql', 'zabbix-frontend-php', 'zabbix-frontend-apache']

    - name: Configurar Zabbix Server
      template:
        src: zabbix_server.conf.j2
        dest: /etc/zabbix/zabbix_server.conf
      notify: Restart Zabbix Server

    - name: Configurar Zabbix Web
      template:
        src: apache2.conf.j2
        dest: /etc/apache2/sites-available/000-default.conf
      notify: Restart Apache

    - name: Import Zabbix database schema
      command: "zcat /usr/share/doc/zabbix-server-pgsql/create.sql.gz | psql -h {{ database_server_1 }} -U {{ zabbix_db_user }} -d {{ zabbix_db_name }} -W"
      become: yes

  handlers:
    - name: Restart Zabbix Server
      service:
        name: zabbix-server
        state: restarted

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
